name: Latest blog post workflow
on:
  push:
    branches:
      - main
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 50
          disable_sort: true
          feed_list: "https://sspai.com/feed,https://feeds.appinn.com/appinns,https://rsshub.app/douban/movie/weekly"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: FCC
          feed_list: "https://www.freecodecamp.org/news/author/_staticvoid/rss"
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: bilibili
          feed_list: "https://rsshub.app/bilibili/ranking/0/3?limit=10"
#      - uses: gautamkrishnar/blog-post-workflow@master
 #       with:
 #          comment_tag_name: MEDIUM
#           feed_list: "https://medium.com/feed/@khaosdoctor"
